function createEmptyProject() {
  return {
    meta: {
      modName: "sampleMod",
      version: "0.1.0",
    },
    division: {
      baseDivision: "",
      alliance: "NATO",
      countryId: "",
      divisionName: "",
      modeSuffix: "multi",
      descriptorExportName: "",
      cfgName: "",
      descriptorId: "",
      divisionNameToken: "",
      summaryTextToken: "",
      historyTextToken: "",
      deckBudget: 50,
      interfaceOrder: null,
      divisionTags: [],
      typeToken: "",
      divisionRule: "",
      costMatrix: "",
      emblemTexture: "",
      standoutUnits: [],
      useCustomEmblem: false,
      emblemFile: null,
      emblemPreviewUrl: "",
    },
    customCountries: [],
    customDivisions: [],
    customDivisionRules: [],
    unitsByCategory: {
      log: [],
      inf: [],
      art: [],
      tnk: [],
      rec: [],
      aa: [],
      hel: [],
      air: [],
    },
    customUnits: [],
    customWeapons: [],
    customAmmo: [],
    files: {
      uiSpecificCountriesText,
      divisionsText,
      localizationText,
      divisionRulesText,
      unitsText,
      deckSerializerText,
    },
    validation: {
      errors: [],
      warnings: [],
    },
  };
}